######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 19 18:15:06 2012
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += src
